; List all worlds that should have the hoth environmental rules like
; ice and snow breaking into blocks and ice freezing when placed.
;
; Example:
;
; hothworlds:
;   - myiceworld
;   - hoth
;
hothworlds:
   - hoth
