name: HothGenerator
version: 1.5
main: biz.orgin.minecraft.hothgenerator.HothGeneratorPlugin
load: STARTUP
description: Generates a really icy world.
commands:
   hothreload:
      description: Reload the hoth configuration file.
      usage: /hothreload
      permission: hothgenerator.hothreload
      permission-message: You don't have permission to use the hothreload command
   hothexport:
      description: Export the selected region to a schematic file.
      usage: /hothexport filename
      permission: hothgenerator.hothexport
      permission-message: You don't have permission to use the hothexport command
permissions:
    hothgenerator.*:
        description: Gives access to all hothgenerator commands
        children:
            hothgenerator.hothreload: true
            hothgenerator.hothexport: true
    hothgenerator.hothreload:
        description: Reload the hoth configuration file.
        default: op
    hothgenerator.hothexport:
        description: Export the selected region to a schematic file.
        default: op
            